---
platform: linux
generator: Ninja
build_tool: vscode_cmake
build_type: Debug
vscode_additional_defines: [ '__EMSCRIPTEN__', 'SOKOL_IMPL', 'SOKOL_GLCORE33', 'SOKOL_GLES3', 'SOKOL_GLES2' ]
defines:
    USE_SOKOL_APP: ON
